### ISSUE TITLE
Linphone integration using Frameworks with enabled non-free codecs doesn't work

### ISSUE THREAD

**Issue by jelenadj** [BelledonneCommunications/linphone-iphone#368]
I am building SDK manually, with additional parameters, and important part for this ticket is:
`DENABLE_NON_FREE_CODECS=ON -DENABLE_G729=ON`
When I integrate this SDK into my project, and put Frameworks into XCode project Embedded Frameworks, I am getting this error:
```
Undefined symbols for architecture armv7:
  "_libmsbcg729_init", referenced from:
      -[LinphoneManager createLinphoneCore] in LinphoneManager.o
ld: symbol(s) not found for architecture armv7
```

However, if I comment out this line from LinphoneManager
`libmsbcg729_init(f);`
build is successful. So, SDK integration using Frameworks works just fine, but when I try to initialize g729 in `createLinphoneCore` I am getting above's error.
In previous version, before switching to Frameworks, g729 worked just fine, and it was built using the same command.

**Comment by ReisBenjamin** [comment]
Hello,

Try to build with non free codecs then clean and rebuild without them please.
This should solve your issue.

Thanks

**Comment by ReisBenjamin** [comment]
Fixed with commit 3d5f8b04474ed6b50c819ca3c8a21b94934ea121

**Comment by jelenadj** [comment]
Thanks. I tried to clean and rebuild without free codecs now, since i already had a build with non-free codecs included, but i am still facing the same issue. Any ideas?

**Comment by joelsdc** [comment]
Hi, any updates on this? I think I might be facing the same problem.

Thanks!

**Comment by ReisBenjamin** [comment]
Hello,

remove the call to libmsbcg729_init(f); it is no longer used in linphone-iphone

**Comment by jelenadj** [comment]
@ReisBenjamin i can understand if linphone sample project is not supposed to have support for g729, but where else should i ask this question for projects that needs to support it? Is there some other kind of support that I can get regarding this issue? Since Linphone provides a possibility to enable non-free codecs, i guess it should be working.

**Comment by ReisBenjamin** [comment]
libmsbcg729 doesn't exist anymore that's why you need to remove this call, it used to be a plugin of mediastreamer2 but it no longer is thus the necessity to remove this call.

**Comment by shraddha-patel-1891** [comment]
@ReisBenjamin 
How to enable g729 codec in the latest linphone ios framework? we enabled in Audio.plist file but not get any effect.
so how to enable it in the latest framework?
if required to build again then please share steps on how to buildd the latest framework.

**Comment by shraddha-patel-1891** [comment]
@ReisBenjamin 
Build g729 using "https://github.com/BelledonneCommunications/bcg729" this library but still not display in the codec list.I am using the latest linphone framework.
so can you please guide me for further steps of display g729 in the codec list after compilation g729?
Thank you
