### ISSUE TITLE
Help me for step 3

### ISSUE THREAD

**Issue by aminawilaga** [BelledonneCommunications/linphone-iphone#56]
I try step 3 n show
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive

when i try (git submodule sync && git submodule update --init --recursive) the result 
fatal: Not a git repository (or any of the parent directories): .git

please help me to finish this problem

**Comment by bagage** [comment]
How did you get linphone-iphone? You should have got it by `git clone https://github.com/BelledonneCommunications/linphone-iphone/ --init --recursive`.

**Comment by aminawilaga** [comment]
now when i run ./prepare.py , the reason
ERROR: The following binaries are missing: nasm. Please install them using:
	brew install nasm

and i do brew install nasm, nasm has been installed and linked with brew, but when i run./prepare.py , always show 
ERROR: The following binaries are missing: nasm. Please install them using:
	brew install nasm

please help me

**Comment by bagage** [comment]
read the readme.

**Comment by aminawilaga** [comment]
i have problem like this, after build SDK

GNU assembler not found, install/update gas-preprocessor

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
make[3]: *** [/Users/admin/linphone-iphone/WORK/ios-armv7/Stamp/EP_ffmpeg/EP_ffmpeg-configure] Error 1
make[2]: *** [CMakeFiles/EP_ffmpeg.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

how i can fix this problem?

**Comment by bagage** [comment]
Update your gas-preprocessor script (see `prepare.py` to know how)

**Comment by aminawilaga** [comment]
after install gas preprocessor i have same problems.

now, what should i do?

**Comment by aminawilaga** [comment]
what xcode version do you have to build linphone-iphone?

**Comment by bagage** [comment]
How did you update it? Please tell me what gives you `which gas-preprocessor.pl && md5 $(which gas-preprocessor.pl)`

**Comment by aminawilaga** [comment]
i update with this code:
wget --no-check-certificate https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl && chmod +x gas-preprocessor.pl && sudo mv gas-preprocessor.pl 

this the result from your last code:
MD5 (/usr/local/bin/gas-preprocessor.pl) = bbf7ae8dd66476d5bf823d8d8dc7474e

i use xcode 7 and sdk ios9.3, it's possible to build or compile linphone-iphone?

**Comment by bagage** [comment]
You did not update it properly. You should have 77fe68235c6d6ec41bb501174a9239e9, not bbf7ae8dd66476d5bf823d8d8dc7474e.

**Comment by aminawilaga** [comment]
how to update gas-preprocessor.pl?

**Comment by bagage** [comment]
Fixed in master, we are now retrieving gas-preprocessor automatically.

**Comment by baixiangguobing** [comment]
I have the same problem with nasm, I still get this error when it's already installed
ERROR: The following binaries are missing: nasm. Please install them using:
brew install nasm

**Comment by rajivudayan** [comment]
Same problem with nasm,
Invalid version of nasm detected. Please make sure that you are NOT using Apple's binary here.

nasm is up to date.

**Comment by rajivudayan** [comment]
Issue solved.Thanks for https://github.com/BelledonneCommunications/linphone-iphone/issues/25
