### ISSUE TITLE
Multiple selection in call history is not working properly

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#75]
Multiple selection in call history is not user friendly:
- Need to touch two times for selection.
- Shows improper cell selection and check marks

Attached screenshot for reference:
![screen shot 2016-05-31 at 1 05 20 pm](https://cloud.githubusercontent.com/assets/17453543/15667122/23457d56-2732-11e6-8a4a-33bf4377ef96.png)

**Comment by bagage** [comment]
Fixed in 93e57c0, thanks 👍

**Comment by nitesh-borad** [comment]
Still facing issue in selecting/deselecting multiple cell rows in UICheckBoxTableView.

Steps to reproduce issue:
1. Go to any screen (Contacts/Chats/Call History), which uses UICheckBoxTableView.
2. Enable edit mode for table by clicking edit button on top right corner of view. Table shows all row with unchecked mark on right side. 
3. Click on multiple rows one by one. It selects rows by showing light gray background color and checked mark on side. This is perfect as expected. No issue here.
4. Deselect any row from selected rows. Now, issue appears. It only removes gray background of cell. But, checked mark is still there.
5. Now again click on the same row. It removes checked box. But, shows gray background.

So, selection of rows by displaying checkbox and gray background for selected row is not synchronized. This is my issue. I guess this will help you to understand.

**Comment by bagage** [comment]
Oh, indeed... thanks for step 4, never notified this. I'll fix it asap.

**Comment by nitesh-borad** [comment]
I have fixed this issue in my project. How can I commit and contribute to linphone-iphone project for this issue fix?

**Comment by bagage** [comment]
The common way of doing it is by:
1. Signing the [contributor agreement](http://www.belledonne-communications.com/downloads/Belledonne_communications_CA.pdf) (needed for licensing issues)
2. Forking this project
3. Cherry picking / reapplying your patch to this project
4. Creating a pull request.
Alternatively you can simply attach your patch somewhere and I'll integrate it manually.

I did not have time to investigate this yet, sorry!

**Comment by nitesh-borad** [comment]
Okay. So, I am adding here the issue fix by sharing screenshot.

Only two lines of source code needed to fix this issue.
![screen shot 2016-06-09 at 3 16 47 pm](https://cloud.githubusercontent.com/assets/17453543/15925909/d21099b2-2e56-11e6-8323-af60563b6b23.png)

1. add line **self.tableView.allowsMultipleSelectionDuringEditing = NO;** in _- (void)viewDidAppear:(BOOL)animated_ method.

2. update **cell.selectionStyle = UITableViewCellSelectionStyleNone;** in _- (void)accessoryForCell:(UITableViewCell *)cell atPath:(NSIndexPath *)indexPath_ method.

I hope you will get issue solved by this. :)

**Comment by bagage** [comment]
Fixed in 77eddee - thanks!
