### ISSUE TITLE
 Libyan country numbers that the first digit of the number is being removed while creating the account.

### ISSUE THREAD

**Issue by NavinVr** [BelledonneCommunications/linphone-iphone#911]
HI,

Why it is happening in Libyan country numbers that the first digit of the number is being removed while creating the account.

![WhatsApp Image 2024-01-10 at 10 03 32 PM](https://github.com/BelledonneCommunications/linphone-iphone/assets/96181463/2f7f8ebe-a4d6-4b10-a1e1-bce68d5fd381)
![WhatsApp Image 2024-01-10 at 10 03 33 PM](https://github.com/BelledonneCommunications/linphone-iphone/assets/96181463/5ae406db-560c-41ff-85d0-5f8825d30e73)

**Comment by NavinVr** [comment]
> HI,
> 
> Why it is happening in Libyan country numbers that the first digit of the number is being removed while creating the account.
> 
> ![WhatsApp Image 2024-01-10 at 10 03 32 PM](https://private-user-images.githubusercontent.com/96181463/297354259-2f7f8ebe-a4d6-4b10-a1e1-bce68d5fd381.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTgyMzMsIm5iZiI6MTcwNTU1NzkzMywicGF0aCI6Ii85NjE4MTQ2My8yOTczNTQyNTktMmY3ZjhlYmUtYTRkNi00YjEwLWExZTEtYmNlNjhkNWZkMzgxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwNjA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTE2YjI0OGMxNDYwMDQ5MGZhNWUzNzZiMDBlNjc1ODY5MzljMTg4ZTViNDViZjk0ZTBkZDBmMjQ0NTAwN2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zeNiCil_EQfAZOH3M5e9s3LSqHCTBhLEkaUihRjGrUA) ![WhatsApp Image 2024-01-10 at 10 03 33 PM](https://private-user-images.githubusercontent.com/96181463/297354282-5ae406db-560c-41ff-85d0-5f8825d30e73.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTgyMzMsIm5iZiI6MTcwNTU1NzkzMywicGF0aCI6Ii85NjE4MTQ2My8yOTczNTQyODItNWFlNDA2ZGItNTYwYy00MWZmLTg1ZDAtNWY4ODI1ZDMwZTczLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwNjA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2VmOWE4ZGYyYzViYzY0OTU5ODcxZDAyMGI0OGMwYTZjNGE2ZjkwMGE4ZTc5ZDE5OThkZDc3ZWYwZGY1NDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChgsKJ7nEfnKNm6himdlFmUxh7t1V8xrBgTtuzEmTVo)

**Comment by NavinVr** [comment]
Hi,
I'm using linphone sdk  pod SDK 5.2.50 in our application. When we are creating a new account in the app, the user enter their number and selects country code. In most of the cases, everything works fine but when the user selects a three digit country code like (Libya - +218). Then the first digit of the number gets omitted automatically from the SDK side.

**Comment by Viish** [comment]
Hi @NavinVr,

You already submitted this issue to our Mantis bugtracker as you were previous clients, and I believe you were already answered there.

That being said, this issue has already been fixed in 5.3 version of our SDK.

Cheers,

**Comment by NavinVr** [comment]
Hi,
I'm using linphone SDK version 'linphone-sdk', '~> 5.3.0-alpha'
in our application. 
 but still have this issue.

**Comment by NavinVr** [comment]
How to solve this Problem？？
[!] CocoaPods could not find compatible versions for pod "linphone-sdk":
  In Podfile:
    linphone-sdk (~> 5.3.0)

None of your spec sources contain a spec satisfying the dependency: `linphone-sdk (~> 5.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by NavinVr** [comment]
Hi,
There is an issue in the code after updating to the latest linphone sdk version. linphone-sdk (~>5.3.10)
     char  *identity_str = _get_identity(account_creator); in AssistantView.m file 
![Screenshot 2024-01-22 at 3 54 49 PM](https://github.com/BelledonneCommunications/linphone-iphone/assets/96181463/a143dfbf-c952-410a-a8aa-22f7ba97018f)
